name: CICD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the source code
      - name: Checkout Source
        uses: actions/checkout@v3
        
      # Step 2: Set up Node.js version (18.x in this case)
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests
      - name: test
        run: npm test
     # Step 6: Save Build Artifacts
      - name: Save Artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
         name: build-artifacts
         path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Đảm bảo chỉ chạy sau khi job 'build' thành công
    if: github.ref == 'refs/heads/main' 

    steps:
      # Step 1: Checkout the source code
      - name: Checkout Source
        uses: actions/checkout@v3

      # Step 2: Download Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      # Step 3: Deploy to Render
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: finalDevops  # Thay bằng tên dịch vụ Azure của bạn
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Thêm Azure Publish Profile secret
          package: .  # Đường dẫn thư mục triển khai (ở đây là thư mục hiện tại)
